<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>SuperMarketStockTakeAPI</AssemblyName>
    <RootNamespace>SuperMarketStockTakeAPI</RootNamespace>
    <Product>SuperMarket StockTake Mod</Product>
    <Version>0.0.1</Version>
    <AssemblyVersion>0.0.1</AssemblyVersion>
    <FileVersion>0.0.1</FileVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>BepInExDll\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony20">
      <HintPath>BepInExDll\0Harmony20.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>SuperMarketDll\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>SuperMarketDll\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>BepInExDll\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>BepInExDll\BepInEx.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader">
      <HintPath>BepInExDll\BepInEx.Preloader.dll</HintPath>
    </Reference>
    <Reference Include="BouncyCastle.Cryptography">
      <HintPath>SuperMarketDll\BouncyCastle.Cryptography.dll</HintPath>
    </Reference>
    <Reference Include="CFXRRuntime">
      <HintPath>SuperMarketDll\CFXRRuntime.dll</HintPath>
    </Reference>
    <Reference Include="Cinemachine">
      <HintPath>SuperMarketDll\Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>SuperMarketDll\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="ConditionalExpression">
      <HintPath>SuperMarketDll\ConditionalExpression.dll</HintPath>
    </Reference>
    <Reference Include="DissonanceVoip">
      <HintPath>SuperMarketDll\DissonanceVoip.dll</HintPath>
    </Reference>
    <Reference Include="Enviro3.Runtime">
      <HintPath>SuperMarketDll\Enviro3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="FizzySteamworks">
      <HintPath>SuperMarketDll\FizzySteamworks.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyXInterop">
      <HintPath>BepInExDll\HarmonyXInterop.dll</HintPath>
    </Reference>
    <Reference Include="kcp2k">
      <HintPath>SuperMarketDll\kcp2k.dll</HintPath>
    </Reference>
    <Reference Include="MeshBakerCore">
      <HintPath>SuperMarketDll\MeshBakerCore.dll</HintPath>
    </Reference>
    <Reference Include="MeshBakerExamples">
      <HintPath>SuperMarketDll\MeshBakerExamples.dll</HintPath>
    </Reference>
    <Reference Include="MeshCombinerCore">
      <HintPath>SuperMarketDll\MeshCombinerCore.dll</HintPath>
    </Reference>
    <Reference Include="MeshCombinerDemo">
      <HintPath>SuperMarketDll\MeshCombinerDemo.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>SuperMarketDll\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.Authenticators">
      <HintPath>SuperMarketDll\Mirror.Authenticators.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.Components">
      <HintPath>SuperMarketDll\Mirror.Components.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.Examples">
      <HintPath>SuperMarketDll\Mirror.Examples.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.Transports">
      <HintPath>SuperMarketDll\Mirror.Transports.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>BepInExDll\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>BepInExDll\Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>BepInExDll\Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>BepInExDll\Mono.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Security">
      <HintPath>SuperMarketDll\Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>BepInExDll\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>BepInExDll\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>SuperMarketDll\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>SuperMarketDll\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>SuperMarketDll\PlayMaker.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>SuperMarketDll\Rewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Windows">
      <HintPath>SuperMarketDll\Rewired_Windows.dll</HintPath>
    </Reference>
    <Reference Include="SimpleWebTransport">
      <HintPath>SuperMarketDll\SimpleWebTransport.dll</HintPath>
    </Reference>
    <Reference Include="SpeechGenerationSystem">
      <HintPath>SuperMarketDll\SpeechGenerationSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition">
      <HintPath>SuperMarketDll\System.ComponentModel.Composition.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration">
      <HintPath>SuperMarketDll\System.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <HintPath>SuperMarketDll\System.Data.DataSetExtensions.dll</HintPath>
    </Reference>
    <Reference Include="System.EnterpriseServices">
      <HintPath>SuperMarketDll\System.EnterpriseServices.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>SuperMarketDll\System.IO.Compression.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>SuperMarketDll\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>SuperMarketDll\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Security">
      <HintPath>SuperMarketDll\System.Security.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel.Internals">
      <HintPath>SuperMarketDll\System.ServiceModel.Internals.dll</HintPath>
    </Reference>
    <Reference Include="System.Transactions">
      <HintPath>SuperMarketDll\System.Transactions.dll</HintPath>
    </Reference>
    <Reference Include="Telepathy">
      <HintPath>SuperMarketDll\Telepathy.dll</HintPath>
    </Reference>
    <Reference Include="UModelerCommon">
      <HintPath>SuperMarketDll\UModelerCommon.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>SuperMarketDll\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging">
      <HintPath>SuperMarketDll\Unity.Animation.Rigging.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging.DocCodeExamples">
      <HintPath>SuperMarketDll\Unity.Animation.Rigging.DocCodeExamples.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>SuperMarketDll\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>SuperMarketDll\Unity.Burst.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>SuperMarketDll\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport">
      <HintPath>SuperMarketDll\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>SuperMarketDll\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>SuperMarketDll\Unity.InputSystem.ForUI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>SuperMarketDll\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.MemoryProfiler">
      <HintPath>SuperMarketDll\Unity.MemoryProfiler.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>SuperMarketDll\Unity.Profiling.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Rendering.LightTransport.Runtime">
      <HintPath>SuperMarketDll\Unity.Rendering.LightTransport.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
      <HintPath>SuperMarketDll\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime.Shared">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Shaders">
      <HintPath>SuperMarketDll\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
    </Reference>
    <Reference Include="Unity.StarterAssets">
      <HintPath>SuperMarketDll\Unity.StarterAssets.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>SuperMarketDll\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>SuperMarketDll\Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Antlr3.Runtime">
      <HintPath>SuperMarketDll\Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>SuperMarketDll\Unity.VisualScripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Flow">
      <HintPath>SuperMarketDll\Unity.VisualScripting.Flow.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.State">
      <HintPath>SuperMarketDll\Unity.VisualScripting.State.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>SuperMarketDll\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>SuperMarketDll\UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>SuperMarketDll\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>SuperMarketDll\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>SuperMarketDll\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>SuperMarketDll\UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>SuperMarketDll\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>SuperMarketDll\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>SuperMarketDll\UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>SuperMarketDll\UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>SuperMarketDll\UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CommandStateObserverModule">
      <HintPath>SuperMarketDll\UnityEngine.CommandStateObserverModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>SuperMarketDll\UnityEngine.ContentLoadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>SuperMarketDll\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>SuperMarketDll\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>SuperMarketDll\UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>SuperMarketDll\UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>SuperMarketDll\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>SuperMarketDll\UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GraphToolsFoundationModule">
      <HintPath>SuperMarketDll\UnityEngine.GraphToolsFoundationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>SuperMarketDll\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HierarchyCoreModule">
      <HintPath>SuperMarketDll\UnityEngine.HierarchyCoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>SuperMarketDll\UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>SuperMarketDll\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>SuperMarketDll\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputForUIModule">
      <HintPath>SuperMarketDll\UnityEngine.InputForUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>SuperMarketDll\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>SuperMarketDll\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>SuperMarketDll\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>SuperMarketDll\UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.MarshallingModule">
      <HintPath>SuperMarketDll\UnityEngine.MarshallingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.MultiplayerModule">
      <HintPath>SuperMarketDll\UnityEngine.MultiplayerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>SuperMarketDll\UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>SuperMarketDll\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>SuperMarketDll\UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>SuperMarketDll\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>SuperMarketDll\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>SuperMarketDll\UnityEngine.ProfilerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>SuperMarketDll\UnityEngine.PropertiesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>SuperMarketDll\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>SuperMarketDll\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>SuperMarketDll\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>SuperMarketDll\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>SuperMarketDll\UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>SuperMarketDll\UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>SuperMarketDll\UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>SuperMarketDll\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>SuperMarketDll\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>SuperMarketDll\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>SuperMarketDll\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>SuperMarketDll\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>SuperMarketDll\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>SuperMarketDll\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>SuperMarketDll\UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>SuperMarketDll\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>SuperMarketDll\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>SuperMarketDll\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>SuperMarketDll\UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>SuperMarketDll\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>SuperMarketDll\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>SuperMarketDll\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>SuperMarketDll\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>SuperMarketDll\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>SuperMarketDll\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>SuperMarketDll\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>SuperMarketDll\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
